apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pytorch-example
  template:
    metadata:
      labels:
        app: pytorch-example
    spec:
      containers:
      - image: pytorch:2.3.0-python3.8-cuda12.1.0-cudnn8-devel-ubuntu22.04
        name: pytorch-example
        ports:
        - containerPort: 22
          protocol: TCP
          name: ssh
        - containerPort: 8888 
          protocol: TCP
          name: jupyterlab
        - containerPort: 6006
          protocol: TCP
          name: tensorboard
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 512Mi
