apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow
  template:
    metadata:
      labels:
        app: tensorflow
    spec:
      containers:
      - name: tensorflow
        image: tensorflow:2.15.0-python3.8-cuda12.1.0-cudnn8-devel-ubuntu22.04
        ports:
        - containerPort: 22
          hostPort: 2222
        - containerPort: 8888
          hostPort: 8888
        - containerPort: 6006
          hostPort: 6006
        resources:
          limits:
            nvidia.com/gpu: "1" # 根据实际情况调整GPU资源限制
        securityContext:
          privileged: true # 如果需要使用GPU，可能需要设置为true