apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-example
  template:
    metadata:
      labels:
        app: ollama-example
    spec:
      containers:
        - image: ollama:python3.10-cuda12.1.0-cudnn8-devel-ubuntu22.04
        name: ollama-example
        ports:
        - containerPort: 22
          protocol: TCP
          name: ssh
        - containerPort: 8888 
          protocol: TCP
          name: jupyterlab
        - containerPort: 6006
          protocol: TCP
          name: tensorboard
        - containerPort: 11434
          protocol: TCP
          name: ollama
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 512Mi
