version: "3"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - ollama-network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"
    depends_on:
      - ollama
    restart: always
    networks:
      - ollama-network

volumes:
  ollama:
  open-webui:

networks:
  ollama-network:
    name: ollama-network
